sudo: false
language: go
go:
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

matrix:
  fast_finish: true
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on

services:
  - postgresql

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)